//! Development-only type export. Internal secrets and persisted configuration
//! never implement TS; the three explicit credential DTOs live in a separate file.
use crate::{
    capabilities::Capabilities,
    credentials::CredentialUpdate,
    error::{AppError, FieldError},
    error_context::{ErrorContext, ErrorDomain},
    ipc::{HistoryUnavailable, NetworkRecoveryResult},
    latency_tasks::{LatencyResult, LatencySubscription, LatencyTaskSnapshot, LatencyTaskState},
    models::{
        AppSettings, ProxyProtocol, RetentionPolicy, RoutingRule, RuleAction, RuleMatcher,
        RuntimeMode,
    },
    observability::{
        ActiveConnection, ActiveConnectionsSnapshot, ConnectionTrend, ObservationStatus,
    },
    route_test::{RouteStage, RouteTestResult},
    runtime::{
        OperationOutcome, OperationResult, RuntimePhase, RuntimeSnapshot, SessionHealth,
        TrafficCoverage,
    },
    services::{ChinaDirectStatus, ProfileCredentialView, ProfileInput, ProfileView},
    store::{DiagnosticFilter, DiagnosticGroup, DiagnosticPage, RuntimeDiagnostic},
};
use ts_rs::TS;

macro_rules! args {
    ($name:ident { $($field:ident: $kind:ty),* $(,)? }) => {
        #[allow(dead_code)]
        #[derive(TS)]
        #[ts(rename_all = "camelCase")]
        struct $name { $($field: $kind),* }
    };
}
args!(IdArgs { id: String });
args!(SelectArgs { id: Option<String> });
args!(ModeArgs { mode: RuntimeMode });
args!(ConfirmedArgs { confirmed: bool });
args!(EnabledArgs { enabled: bool });
args!(RouteArgs {
    target: String,
    port: u16
});
args!(RulesArgs { rules: Vec<RoutingRule> });
args!(OrderArgs { ids: Vec<String> });
args!(SettingsArgs {
    settings: AppSettings
});
args!(SubscriptionArgs {
    subscription_id: String
});
args!(SaveArgs {
    input: ProfileInput
});
args!(ImportArgs { json: String, updates: std::collections::HashMap<String, CredentialUpdate> });
args!(DiagnosticsArgs {
    filter: DiagnosticFilter,
    offset: usize,
    limit: usize
});
args!(DiagnosticReportArgs {
    filter: DiagnosticFilter
});
args!(ClearArgs {
    filter: DiagnosticFilter,
    confirmed: bool
});

#[allow(dead_code)]
#[derive(TS)]
struct HistoryArgs {
    #[ts(type = "unknown", optional)]
    _filter: Option<serde_json::Value>,
    #[ts(optional)]
    _cursor: Option<String>,
}

// Tauri transports serde_json numbers, including u64/i64. ts-rs's default
// bigint representation describes other transports; adapt declarations here.
fn json_numbers(source: String) -> String {
    source.replace("bigint", "number")
}
fn declaration<T: TS>() -> String {
    format!("export {}\n", json_numbers(T::decl()))
}
fn entry<A: TS, R: TS>(name: &str) -> String {
    format!(
        "  {name}: [{}, {}];\n",
        json_numbers(A::inline()),
        json_numbers(R::name())
    )
}

fn public_contract() -> String {
    let mut output = String::from("// Generated by pnpm ipc:generate. Do not edit.\nimport type { CredentialUpdate, ProfileInput, ProfileCredentialView } from './credentials';\n");
    macro_rules! types { ($($kind:ty),* $(,)?) => { $(output.push_str(&declaration::<$kind>());)* }; }
    types!(
        Capabilities,
        ChinaDirectStatus,
        ProfileView,
        ErrorDomain,
        ErrorContext,
        AppError,
        FieldError,
        ProxyProtocol,
        RuntimeMode,
        RuleMatcher,
        RuleAction,
        RoutingRule,
        RetentionPolicy,
        AppSettings,
        ActiveConnection,
        ConnectionTrend,
        ActiveConnectionsSnapshot,
        ObservationStatus,
        RouteStage,
        RouteTestResult,
        SessionHealth,
        OperationOutcome,
        OperationResult,
        RuntimePhase,
        TrafficCoverage,
        RuntimeSnapshot,
        LatencyResult,
        LatencyTaskState,
        LatencyTaskSnapshot,
        LatencySubscription,
        RuntimeDiagnostic,
        DiagnosticFilter,
        DiagnosticPage,
        DiagnosticGroup,
        NetworkRecoveryResult,
        HistoryUnavailable
    );
    output.push_str("export type CommandMap = {\n");
    macro_rules! commands { ($($name:ident: $args:ty => $result:ty),* $(,)?) => { $(output.push_str(&entry::<$args, $result>(stringify!($name)));)* }; }
    commands!(
        acknowledge_frontend_ready: () => bool,
        get_capabilities: () => Capabilities,
        get_connection_history: HistoryArgs => HistoryUnavailable,
        list_profiles: () => Vec<ProfileView>,
        get_profile_credential: IdArgs => ProfileCredentialView,
        save_profile: SaveArgs => ProfileView,
        delete_profile: IdArgs => (),
        select_profile: SelectArgs => (),
        list_rules: () => Vec<RoutingRule>,
        replace_rules: RulesArgs => (),
        reorder_rules: OrderArgs => (),
        get_settings: () => AppSettings,
        update_settings: SettingsArgs => AppSettings,
        get_china_direct_status: () => ChinaDirectStatus,
        set_china_direct_enabled: EnabledArgs => ChinaDirectStatus,
        test_route: RouteArgs => RouteTestResult,
        export_configuration: () => String,
        save_configuration: () => bool,
        import_configuration: ImportArgs => (),
        get_runtime_snapshot: () => RuntimeSnapshot,
        export_runtime_snapshot: () => String,
        validate_configuration: () => String,
        set_runtime_mode: ModeArgs => RuntimeSnapshot,
        stop_runtime: () => RuntimeSnapshot,
        recover_network: ConfirmedArgs => NetworkRecoveryResult,
        get_active_connections: () => ActiveConnectionsSnapshot,
        copy_active_connection_detail: IdArgs => String,
        get_runtime_diagnostics: DiagnosticsArgs => DiagnosticPage,
        get_diagnostic_groups: DiagnosticReportArgs => Vec<DiagnosticGroup>,
        export_runtime_diagnostics: DiagnosticReportArgs => String,
        save_runtime_diagnostics: DiagnosticReportArgs => bool,
        clear_runtime_diagnostics: ClearArgs => usize,
        start_proxy_latency_task: IdArgs => LatencySubscription,
        get_proxy_latency_task: SubscriptionArgs => LatencyTaskSnapshot,
        release_proxy_latency_task: SubscriptionArgs => (),
        test_proxy_latency: IdArgs => LatencyResult,
    );
    output.push_str("};\n");
    output
}

#[test]
fn generate_ipc_contract() {
    let public = public_contract();
    let handler = include_str!("lib.rs")
        .split("tauri::generate_handler![")
        .nth(1)
        .unwrap()
        .split("])")
        .next()
        .unwrap();
    for line in handler
        .lines()
        .map(str::trim)
        .filter(|line| !line.is_empty())
    {
        let name = line.trim_end_matches(',').rsplit("::").next().unwrap();
        assert!(
            public.contains(&format!("  {name}:")),
            "registered command missing: {name}"
        );
    }
    for internal in [
        "credential_ref",
        "ProxyCredential",
        "PersistedConfiguration",
        "LatencyInput",
        "password:",
    ] {
        assert!(
            !public.contains(internal),
            "internal boundary leaked: {internal}"
        );
    }
    let mut secret = String::from("// Generated explicit credential IPC boundary. Do not edit or log values.\nimport type { ProxyProtocol } from './ipc';\n");
    secret.push_str(&declaration::<CredentialUpdate>());
    secret.push_str(&declaration::<ProfileInput>());
    secret.push_str(&declaration::<ProfileCredentialView>());
    if let Some(directory) = std::env::var_os("SOCKS_PROXY_CONTRACT_OUTPUT") {
        let directory = std::path::PathBuf::from(directory);
        std::fs::create_dir_all(&directory).unwrap();
        std::fs::write(directory.join("ipc.ts"), public).unwrap();
        std::fs::write(directory.join("credentials.ts"), secret).unwrap();
    }
}

#[test]
fn public_wire_values_match_generated_enums_numbers_and_error_shape() {
    let prediction = RouteTestResult {
        target: "example.com".into(),
        port: 443,
        configuration_revision: 7,
        stage: RouteStage::UserRule,
        action: RuleAction::Direct,
        proxy_profile_id: None,
        proxy_name: None,
        matched_rule_id: Some("first".into()),
        matched_rule_name: Some("First".into()),
        reason: "首条用户规则".into(),
        data_date: None,
    };
    let value = serde_json::to_value(prediction).unwrap();
    assert_eq!(value["stage"], "user_rule");
    assert_eq!(value["configuration_revision"], 7);
    assert_eq!(value["port"], 443);
    assert!(value["proxy_profile_id"].is_null());
    let stage = RouteStage::decl();
    for name in [
        "user_rule",
        "china_domain",
        "private_ip",
        "china_ip",
        "final",
    ] {
        assert!(stage.contains(name));
    }
    for state in [
        LatencyTaskState::Queued,
        LatencyTaskState::Running,
        LatencyTaskState::Cancelling,
        LatencyTaskState::Cancelled,
        LatencyTaskState::Succeeded,
        LatencyTaskState::Failed,
    ] {
        let wire = serde_json::to_value(state).unwrap();
        assert!(LatencyTaskState::decl().contains(wire.as_str().unwrap()));
    }
    let error = serde_json::to_value(AppError::unavailable("测试不可用")).unwrap();
    assert_eq!(error["code"], "unavailable");
    assert_eq!(error["message"], "测试不可用");
    assert_eq!(error["fields"], serde_json::json!([]));
    // Only this explicit DTO carries plaintext credentials over the command boundary.
    let credential = serde_json::to_value(ProfileCredentialView {
        username: "synthetic-user".into(),
        password: "synthetic-secret".into(),
    })
    .unwrap();
    assert_eq!(credential.as_object().unwrap().len(), 2);
    assert!(!public_contract().contains("synthetic-secret"));
}

#[test]
fn runtime_mode_parameters_match_wire_and_generated_contract() {
    for use_china_direct in [false, true] {
        for default_action in [RuleAction::Proxy, RuleAction::Direct] {
            let mode = RuntimeMode::Rules {
                use_china_direct,
                default_action,
            };
            let wire = serde_json::json!({"rules": {
                "use_china_direct": use_china_direct,
                "default_action": default_action,
            }});
            assert_eq!(serde_json::to_value(mode).unwrap(), wire);
            assert_eq!(serde_json::from_value::<RuntimeMode>(wire).unwrap(), mode);
        }
    }
    for (mode, wire) in [
        (RuntimeMode::Global, "global"),
        (RuntimeMode::Direct, "direct"),
    ] {
        assert_eq!(serde_json::to_value(mode).unwrap(), wire);
        assert_eq!(
            serde_json::from_value::<RuntimeMode>(wire.into()).unwrap(),
            mode
        );
    }
    for invalid in [
        serde_json::json!("rules"),
        serde_json::json!({"rules": {"use_china_direct": false}}),
        serde_json::json!({"rules": {"use_china_direct": false, "default_action": "reject"}}),
    ] {
        assert!(serde_json::from_value::<RuntimeMode>(invalid).is_err());
    }
    let declaration = RuntimeMode::decl();
    assert!(declaration.contains("use_china_direct: boolean"));
    assert!(declaration.contains("default_action: RuleAction"));
    assert!(public_contract().contains(&format!("export {declaration}")));
}
